# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ab00d3345f5e130be6f11f6e9fcbb03d14cdb82969e9a646e2f3896e9a40382bf32f4362fad8b226c82a05f143d32453d830ddcd0011c91e51f0e113c0b7bd4

test:
  secret_key_base: e0d6dd8447202e5d51e104109232c116772f135b07d0957bd7df42e2b0b1309919555e368225d418356a1ddd6b2cbe0d17c89d850cebdf43490aff1e9614e573

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
